# Generated by Django 5.2.14 on 2026-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('total_days', models.IntegerField()),
                ('from_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('from_city_arrival_time', models.TimeField()),
                ('from_city_departure_time', models.TimeField()),
                ('destination_arrival_time', models.TimeField()),
                ('destination_departure_time', models.TimeField()),
                ('total_business_seats', models.IntegerField()),
                ('total_economy_seats', models.IntegerField()),
                ('business_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economy_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_image', models.ImageField(upload_to='flights/')),
                ('airport_name', models.CharField(max_length=100)),
            ],
        ),
    ]
