# Generated by Django 5.2.14 on 2026-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('airport_name', models.CharField(max_length=100)),
                ('airport_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('description', models.TextField()),
            ],
        ),
    ]
