# Generated by Django 5.2.14 on 2026-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
