# Generated by Django 5.2.14 on 2026-06-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0004_booking_selected_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
