# Generated by Django 5.2.14 on 2026-06-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_image',
            field=models.ImageField(blank=True, null=True, upload_to='flights/'),
        ),
    ]
